### ISSUE TITLE
Error in command line arguments mentioned in Readme file

### ISSUE THREAD

**Issue by GURPREET-WEB** [pxqian/FedAFA#1]
Dear friend,

There is no any main.py file that you referred to in the readme file. Additionally, could you please check and update errors in the command arguments mentioned for running the code? I also tried by replacing main.py with fedafa.py, but I am still encountering errors. Thanks

**Comment by pxqian** [comment]
The reason for the failure of the fedafa.py may be the lack of loading the pre-trained model. This pre-trained model is trained using the fedavg algorithm.You can have a try.

**Comment by pxqian** [comment]
The reason for the failure of the fedafa.py may be the lack of loading the pre-trained model. This pre-trained model is trained using the fedavg algorithm.You can have a try.
